Use 'bundle exec' to invoke 'whenever' gem (#71)
`bundle list whenever` prints the path to the gem in Bundler 1.16, but
in Bundler 2 it produces the following error:

    ERROR: "bundle list" was called with arguments ["whenever"]
    Usage: "bundle list"

The modern way to print the path is `bundle info whenever --path`.

But there is no reason to do that when we can use `bundle exec whenever`
(as the 'whenever' README[1] now shows). This is what our install
script used to do, until it was changed with no explanation in commit
28355a5 ("further install reorganisation - additional dependencies
added to install scripts", 2013-02-08).

Changing it back to 'bundle exec'.

[1] https://github.com/javan/whenever/blob/b205bcdea336/README.md#the-whenever-command