Pin ranked-model to < 0.4.3 because 0.4.3 - 0.4.4 break our migrations
While attempting to upgrade to Rails 4.1, we discovered that
ranked-model versions 0.4.3 and 0.4.4 break some of our migrations.

See https://www.github.com/brendon/ranked-model/issues/139 for a
similar issue caused by the same code change. In our case, we also
need the fix in https://www.github.com/brendon/ranked-model/pull/152
(released in 0.4.5).

In short, ranked-model 0.4.3 added a check that raises an error if the
rank column has a default value. This check tries to access the
database so it raises an error if the database or the table don't
exist (proper graceful handling was only added in 0.4.5).

Some of our data migrations use the models, which can be problematic
(https://jakeyesbeck.com/2021/04/10/avoid-models-in-migrations/). In
this particular case, a table was renamed, and some old migrations
referred to a model. When a model class (referenced directly or
indirectly) is loaded and calls `ranks`, ranked-model 0.4.3 tries to
access the model's table, and that fails because at that point the
table still has the old name. Hence the breakage.

So we can either change our migrations to avoid using models (#182;
can just delete problematic migration code because the data in our
production database has already been migrated), or we can stay away
from ranked-model 0.4.3 - 0.4.4. Pinning ranked-model is easier.

We can't update to ranked-model 0.4.5 yet because it depends on
activerecord >= 4.2 but we are on Rails 4.0.13. We can't even update
to ranked-model 0.4.2 because it depends on activerecord >= 4.1.16. So
this commit simply stays on ranked-model 0.4.0, and adds a pin to make
sure that we stay on < 0.4.3, until we can update to 0.4.5.

(Aside: see https://github.com/ilyakatz/data-migrate for a relevant
tool that helps separate data migrations for schema migrations.)

Here is the full stack trace when trying to update to ranked-model
0.4.3 (it's a little hard to reproduce because it requires updating
Rails to 4.1.16):

```
$ rake db:migrate
...
== 20131206074948 NameAllTestSetsAndCases: migrating ==========================
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::UndefinedTable: ERROR:  relation "problem_set_problems" does not exist
LINE 5:                WHERE a.attrelid = '"problem_set_problems"'::...
                                          ^
:               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
                FROM pg_attribute a LEFT JOIN pg_attrdef d
                  ON a.attrelid = d.adrelid AND a.attnum = d.adnum
               WHERE a.attrelid = '"problem_set_problems"'::regclass
                 AND a.attnum > 0 AND NOT a.attisdropped
               ORDER BY a.attnum
.../gems/activerecord-4.1.16/lib/active_record/connection_adapters/postgresql_adapter.rb:822:in `async_exec'
.../gems/activerecord-4.1.16/lib/active_record/connection_adapters/postgresql_adapter.rb:822:in `block in exec_no_cache'
.../gems/activerecord-4.1.16/lib/active_record/connection_adapters/abstract_adapter.rb:378:in `block in log'
.../gems/activesupport-4.1.16/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
.../gems/activerecord-4.1.16/lib/active_record/connection_adapters/abstract_adapter.rb:372:in `log'
.../gems/activerecord-4.1.16/lib/active_record/connection_adapters/postgresql_adapter.rb:822:in `exec_no_cache'
.../gems/activerecord-4.1.16/lib/active_record/connection_adapters/postgresql/database_statements.rb:137:in `exec_query'
.../gems/activerecord-4.1.16/lib/active_record/connection_adapters/postgresql_adapter.rb:976:in `column_definitions'
.../gems/activerecord-4.1.16/lib/active_record/connection_adapters/postgresql/schema_statements.rb:187:in `columns'
.../gems/activerecord-4.1.16/lib/active_record/connection_adapters/schema_cache.rb:93:in `block in prepare_default_proc'
.../gems/activerecord-4.1.16/lib/active_record/connection_adapters/schema_cache.rb:44:in `columns'
.../gems/activerecord-4.1.16/lib/active_record/model_schema.rb:214:in `columns'
.../gems/activerecord-4.1.16/lib/active_record/model_schema.rb:255:in `column_defaults'
.../gems/activerecord-4.1.16/lib/active_record/locking/optimistic.rb:174:in `column_defaults'
.../gems/ranked-model-0.4.3/lib/ranked-model.rb:51:in `ranks'
.../nztrain/app/models/problem_set_problem.rb:10:in `<class:ProblemSetProblem>'
.../nztrain/app/models/problem_set_problem.rb:1:in `<top (required)>'
.../gems/activesupport-4.1.16/lib/active_support/dependencies.rb:443:in `load'
.../gems/activesupport-4.1.16/lib/active_support/dependencies.rb:443:in `block in load_file'
.../gems/activesupport-4.1.16/lib/active_support/dependencies.rb:633:in `new_constants_in'
.../gems/activesupport-4.1.16/lib/active_support/dependencies.rb:442:in `load_file'
.../gems/activesupport-4.1.16/lib/active_support/dependencies.rb:342:in `require_or_load'
.../gems/activesupport-4.1.16/lib/active_support/dependencies.rb:480:in `load_missing_constant'
.../gems/activesupport-4.1.16/lib/active_support/dependencies.rb:180:in `const_missing'
.../gems/activesupport-4.1.16/lib/active_support/dependencies.rb:512:in `load_missing_constant'
.../gems/activesupport-4.1.16/lib/active_support/dependencies.rb:180:in `const_missing'
.../nztrain/app/models/problem.rb:4:in `<class:Problem>'
.../nztrain/app/models/problem.rb:1:in `<top (required)>'
.../gems/activesupport-4.1.16/lib/active_support/dependencies.rb:443:in `load'
.../gems/activesupport-4.1.16/lib/active_support/dependencies.rb:443:in `block in load_file'
.../gems/activesupport-4.1.16/lib/active_support/dependencies.rb:633:in `new_constants_in'
.../gems/activesupport-4.1.16/lib/active_support/dependencies.rb:442:in `load_file'
.../gems/activesupport-4.1.16/lib/active_support/dependencies.rb:342:in `require_or_load'
.../gems/activesupport-4.1.16/lib/active_support/dependencies.rb:480:in `load_missing_constant'
.../gems/activesupport-4.1.16/lib/active_support/dependencies.rb:180:in `const_missing'
.../gems/activesupport-4.1.16/lib/active_support/dependencies.rb:512:in `load_missing_constant'
.../gems/activesupport-4.1.16/lib/active_support/dependencies.rb:180:in `const_missing'
.../nztrain/db/migrate/20131206074948_name_all_test_sets_and_cases.rb:5:in `up'
...
```

Co-authored-by: Ben Anderson <benanderson@acidic.co.nz>