Fix crash in /submissions/my when not signed in
We need to check that we have a current user before using
current_user.id.

Error trace:

```
NoMethodError (undefined method `id' for nil:NilClass):
  app/controllers/submissions_controller.rb:19:in `index'
```