Install Bundler 1.x instead of latest version (2.4) (#158)
Install Bundler 1.x instead of latest version (2.4)

The recently-released Bundler 2.4 requires Ruby >= 2.6, but we use
Ruby 2.3.8 so `gem install bundler` fails with

```
ERROR:  Error installing bundler:
        bundler requires Ruby version >= 2.6.0.
```

But even earler 2.x versions don't work well. `bundle install`
succeeds, but displays the following warning:

```
Your lockfile doesn't include a valid resolution.
You can fix this by regenerating your lockfile or trying to manually editing the bad locked gems to a version that satisfies all dependencies.
The unmet dependencies are:
* bundler (< 2.0, >= 1.3.0), depended upon rails-4.0.13, unsatisfied by bundler-2.3.26
```

And `bundle update <gem>` fails altogether:

```
Bundler could not find compatible versions for gem "bundler":
  In Gemfile:
    rails (~> 4.0.0) was resolved to 4.0.13, which depends on
      bundler (< 2.0, >= 1.3.0)

  Current Bundler version:
    bundler (2.3.26)
```

So change the install script to use Bundler 1.x.

Note that this is relevant when using rbenv, but not when using RVM
because RVM includes Bundler by default:
https://github.com/rvm/rvm/blame/9d55c729d536dab23982946a5b65d10d0301ff78/docs/upgrade-notes.md#L29

Co-authored-by: Jonathan Khoo <jkhoo98@gmail.com>