Fix 'Unknown key: null' in create_settings db migration
It looks like add_index doesn't support the option :null.

$ bundle exec rake db:migrate
== 20120128000525 CreateSettings: migrating ===================================
-- create_table(:settings)
   -> 0.0106s
-- add_index(:settings, :key, {:unique=>true, :null=>false})
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

Unknown key: null
.../gems/activesupport-4.0.13/lib/active_support/core_ext/hash/keys.rb:70:in `block in assert_valid_keys'
.../gems/activesupport-4.0.13/lib/active_support/core_ext/hash/keys.rb:69:in `each_key'
.../gems/activesupport-4.0.13/lib/active_support/core_ext/hash/keys.rb:69:in `assert_valid_keys'
.../gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract/schema_statements.rb:783:in `add_index_options'
.../gems/activerecord-4.0.13/lib/active_record/connection_adapters/postgresql/schema_statements.rb:438:in `add_index'
.../gems/activerecord-4.0.13/lib/active_record/migration.rb:629:in `block in method_missing'
.../gems/activerecord-4.0.13/lib/active_record/migration.rb:601:in `block in say_with_time'
.../gems/activerecord-4.0.13/lib/active_record/migration.rb:601:in `say_with_time'
.../gems/activerecord-4.0.13/lib/active_record/migration.rb:621:in `method_missing'
.../gems/activerecord-4.0.13/lib/active_record/migration.rb:387:in `method_missing'
.../nztrain/db/migrate/20120128000525_create_settings.rb:7:in `up'

(schema.rb is automatically generated.)