Lock Bundler version to < 2.4
The recently-released Bundler 2.4 requires Ruby >= 2.6, but we use
Ruby 2.3.8 so "gem install bundler" fails with

```
ERROR:  Error installing bundler:
        bundler requires Ruby version >= 2.6.0.
```

Note that this is relevant when using rbenv, but not when using rvm
because it includes Bundler by default:
https://github.com/rvm/rvm/blame/9d55c729d536dab23982946a5b65d10d0301ff78/docs/upgrade-notes.md#L29